language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-pip
    - sudo pip install fabric
    - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - pip install -r fabric/requirements.txt
    - pip install coveralls --use-mirrors
install:
    - cd fabric; fab provision:test_server -H localhost -i ~/.ssh/id_rsa; cd ~/
script: sudo -u postgres psql -d postgres -c "ALTER ROLE localwiki SUPERUSER;"; source /srv/localwiki/env/bin/activate; pip install coveralls --use-mirrors; coverage run --source=localwiki /srv/localwiki/src/localwiki/manage.py test regions pages maps tags versioning diff ckeditor redirects users
after_success:
    - source /srv/localwiki/env/bin/activate; coveralls
