language: python
python:
    - "2.7"
before_install:
    - sudo apt-get update
    - sudo apt-get install python-pip
    - sudo pip install fabric
    - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
    - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
    - pip install -r fabric/requirements.txt
    - cp fabric/config_secrets.py.template fabric/config_secrets.py
install:
    - cd fabric; fab provision -H localhost -i ~/.ssh/id_rsa
script: coverage run --source=localwiki localwiki/manage.py test regions pages maps tags versioning diff ckeditor redirects users
after_success:
    - coveralls
